AllCops:
  NewCops: enable

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "active_statsd.gemspec"

Layout/LineLength:
  Max: 120

ThreadSafety/DirChdir:
  Exclude:
    - "active_statsd.gemspec"

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-thread_safety
